### ISSUE TITLE
Blog have issue on change page.

### ISSUE THREAD

**Issue by adam429** [aisensiy/aisensiy.github.com#1]
http://aisensiy.github.io/page2/

At the bottom on this page, there are two buttons [Older] / [Newer] 

The [Older] Button is linked to a 404 page (http://aisensiy.github.io/page2/page3)
The [Newer] Button is linked to self page (http://aisensiy.github.io/page2), cannot back to page 1.

My browser is Chrome Version 73.0.3683.103 (Official Build) (64-bit) on Mac OS

**Comment by aisensiy** [comment]
Thanks for your issue. This is fixed.
